### PR TITLE
Fix license metadata

### PR DESCRIPTION
**Pull request by mattwthompson**
not sure where else to check:

```shell
$ grep -r MIT .
./LICENSE.txt:AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
./LICENSE.txt:DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
```

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.
  - I actually grabbed the most recent `.conda` file, unzipped it, and found the expected CC-BY-4.0 license in `pkg-openff-nagl-models-0.3.0-pyhd8ed1ab_0.tar.zst`

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by lilyminium** [comment]
🤦‍♀️ Oops. Thanks very much for noticing and putting the fix in. Do we need additional builds with the correct license for the other versions too do you reckon?

**Review by lilyminium — APPROVED** [review]
LGTM!

**Comment by mattwthompson** [comment]
IANAL but I'm okay with not patching old builds because
1. I think these fields really are metadata, i.e. the license file in the package is the source of truth in a conflict, and I think that's always been correct
2. There isn't much reason to use old versions given that the latest release still pulls in new models (right?)
3. The difference between MIT and CC-BY-4.0 in the current user base is not so large. If this matters to companies, I'd expect them to do their due diligence and look at the license in the package, not just the conda metadata

**Pull request merged**
